// <auto-generated />
using System;
using ERP.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824135341_InitialERPSetup")]
    partial class InitialERPSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Domain.Model.CompanyWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapacitySquareMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyWarehouses");
                });

            modelBuilder.Entity("ERP.Domain.Model.ContractPaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPaymentRecords");
                });

            modelBuilder.Entity("ERP.Domain.Model.ContractProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MaxPenaltyAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PenaltyClauseNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PenaltyPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SignDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ContractProjects");
                });

            modelBuilder.Entity("ERP.Domain.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyWarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentType")
                        .HasColumnType("int");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyWarehouseId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("EquipmentPurchases");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipmentPurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentPurchaseId");

                    b.ToTable("EquipmentPurchaseItems");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchasePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EquipmentPurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("EquipmentPurchaseId");

                    b.ToTable("EquipmentPurchasePayments");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment_Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Equipment_Maintenances");
                });

            modelBuilder.Entity("ERP.Domain.Model.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ERP.Domain.Model.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaterialType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("MaterialPurchases");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialPurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialPurchaseId");

                    b.ToTable("MaterialPurchaseItems");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchasePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MaterialPurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("MaterialPurchaseId");

                    b.ToTable("MaterialPurchasePayments");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_1_Project_Site_Management.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.CompanyWarehouseStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyWarehouseId")
                        .HasColumnType("int");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceivedByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyWarehouseId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.ToTable("CompanyWarehouseStocks");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.MaterialConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectWarehouseStockId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPhaseId");

                    b.HasIndex("ProjectWarehouseStockId");

                    b.ToTable("MaterialConsumptions");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.OrderMaterials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderId1");

                    b.ToTable("OrderMaterials");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.ProjectWarehouseStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectWarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReceivedByEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectWarehouseId");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.ToTable("ProjectWarehouseStocks");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2___Procurement___Inventory.PhaseMaterialRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProjectPhaseId");

                    b.ToTable("PhaseMaterialRequirements");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_3___Equipment_Machinery.MaintenanceEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("Equipment_MaintenanceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Equipment_MaintenanceId");

                    b.ToTable("MaintenanceEmployees");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_3___Equipment_Machinery.ProjectEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEquipment");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ContractInstallmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("MonthsAfterSignDate")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractInstallmentPlans");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ProjectExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPhaseId");

                    b.ToTable("ProjectExpenses");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ProjectFinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualProfitLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActualRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectFinancialSnapshots");
                });

            modelBuilder.Entity("ERP.Domain.Model.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("ERP.Domain.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectOrderRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectOrderRequests");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CapacitySquareMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWarehouses");
                });

            modelBuilder.Entity("ERP.Domain.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ERP.Domain.Model.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ContractSigningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("ERP.Domain.Model.SupplierMaterialPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierMaterialPrices");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.ProjectEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectEmployees");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualCostCalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("FinishedDate")
                        .HasColumnType("date");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPhases");
                });

            modelBuilder.Entity("ERP.Domain.Model.ContractPaymentRecord", b =>
                {
                    b.HasOne("ERP.Domain.Model.ContractProject", "ContractProject")
                        .WithMany("ContractPaymentRecords")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractProject");
                });

            modelBuilder.Entity("ERP.Domain.Model.ContractProject", b =>
                {
                    b.HasOne("ERP.Domain.Model._1_Project_Site_Management.Client", "Client")
                        .WithMany("ContractProjects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithOne("ContractProject")
                        .HasForeignKey("ERP.Domain.Model.ContractProject", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.Employee", b =>
                {
                    b.HasOne("ERP.Domain.Model.Module_1_Project_Site_Management.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment", b =>
                {
                    b.HasOne("ERP.Domain.Model.CompanyWarehouse", "CompanyWarehouse")
                        .WithMany("Equipment")
                        .HasForeignKey("CompanyWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERP.Domain.Model.Supplier", "Supplier")
                        .WithMany("Equipments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyWarehouse");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchase", b =>
                {
                    b.HasOne("ERP.Domain.Model.Supplier", "Supplier")
                        .WithMany("EquipmentPurchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchaseItem", b =>
                {
                    b.HasOne("ERP.Domain.Model.Equipment", "Equipment")
                        .WithMany("EquipmentPurchaseItem")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.EquipmentPurchase", "EquipmentPurchase")
                        .WithMany("EquipmentPurchaseItems")
                        .HasForeignKey("EquipmentPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("EquipmentPurchase");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchasePayment", b =>
                {
                    b.HasOne("ERP.Domain.Model.EquipmentPurchase", "EquipmentPurchase")
                        .WithMany("EquipmentPurchasePayments")
                        .HasForeignKey("EquipmentPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentPurchase");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment_Maintenance", b =>
                {
                    b.HasOne("ERP.Domain.Model.Equipment", "Equipment")
                        .WithMany("Equipment_Maintenances")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchase", b =>
                {
                    b.HasOne("ERP.Domain.Model.Supplier", "Supplier")
                        .WithMany("MaterialPurchases")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchaseItem", b =>
                {
                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("MaterialPurchaseItem")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.MaterialPurchase", "MaterialPurchase")
                        .WithMany("MaterialPurchaseItems")
                        .HasForeignKey("MaterialPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialPurchase");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchasePayment", b =>
                {
                    b.HasOne("ERP.Domain.Model.MaterialPurchase", "MaterialPurchase")
                        .WithMany("Payments")
                        .HasForeignKey("MaterialPurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialPurchase");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.CompanyWarehouseStock", b =>
                {
                    b.HasOne("ERP.Domain.Model.CompanyWarehouse", "CompanyWarehouse")
                        .WithMany("CompanyWarehouseStocks")
                        .HasForeignKey("CompanyWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("CompanyWarehouseStocks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("CompanyWarehouseStocks")
                        .HasForeignKey("ReceivedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyWarehouse");

                    b.Navigation("Employee");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.MaterialConsumption", b =>
                {
                    b.HasOne("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", "ProjectPhase")
                        .WithMany("MaterialConsumptions")
                        .HasForeignKey("ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Module_2__Procurement_Inventory.ProjectWarehouseStock", "ProjectWarehouseStock")
                        .WithMany("MaterialConsumptions")
                        .HasForeignKey("ProjectWarehouseStockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectPhase");

                    b.Navigation("ProjectWarehouseStock");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.OrderMaterials", b =>
                {
                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("OrderMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.ProjectOrderRequest", "Order")
                        .WithMany("OrderMaterials")
                        .HasForeignKey("OrderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.ProjectWarehouseStock", b =>
                {
                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("ProjectWarehouseStocks")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.ProjectWarehouse", "ProjectWarehouse")
                        .WithMany("ProjectWarehouseStocks")
                        .HasForeignKey("ProjectWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("ProjectWarehouseStocks")
                        .HasForeignKey("ReceivedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Material");

                    b.Navigation("ProjectWarehouse");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2___Procurement___Inventory.PhaseMaterialRequirement", b =>
                {
                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("PhaseMaterialRequirements")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", "ProjectPhase")
                        .WithMany("ProjectMaterials")
                        .HasForeignKey("ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProjectPhase");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_3___Equipment_Machinery.MaintenanceEmployee", b =>
                {
                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("MaintenanceEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Equipment_Maintenance", "Equipment_Maintenance")
                        .WithMany("MaintenanceEmployees")
                        .HasForeignKey("Equipment_MaintenanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Equipment_Maintenance");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_3___Equipment_Machinery.ProjectEquipment", b =>
                {
                    b.HasOne("ERP.Domain.Model.Equipment", "Equipment")
                        .WithMany("ProjectEquipment")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("ProjectEquipment")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ContractInstallmentPlan", b =>
                {
                    b.HasOne("ERP.Domain.Model.ContractProject", "ContractProject")
                        .WithMany("ContractPaymentPlans")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractProject");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ProjectExpense", b =>
                {
                    b.HasOne("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", "ProjectPhase")
                        .WithMany("ProjectExpenses")
                        .HasForeignKey("ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectPhase");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_4___Finance.ProjectFinancialSnapshot", b =>
                {
                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("ProjectFinancialSnapshots")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("FinancialSnapshots")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.Project", b =>
                {
                    b.HasOne("ERP.Domain.Model._1_Project_Site_Management.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectOrderRequest", b =>
                {
                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("ProjectOrderRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("ProjectOrderRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectWarehouse", b =>
                {
                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("ProjectWarehouses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.SupplierMaterialPrice", b =>
                {
                    b.HasOne("ERP.Domain.Model.Material", "Material")
                        .WithMany("SupplierMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Supplier", "Supplier")
                        .WithMany("SupplierMaterials")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.ProjectEmployee", b =>
                {
                    b.HasOne("ERP.Domain.Model.Employee", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", b =>
                {
                    b.HasOne("ERP.Domain.Model.Phase", "Phase")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Model.Project", "Project")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ERP.Domain.Model.CompanyWarehouse", b =>
                {
                    b.Navigation("CompanyWarehouseStocks");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ERP.Domain.Model.ContractProject", b =>
                {
                    b.Navigation("ContractPaymentPlans");

                    b.Navigation("ContractPaymentRecords");
                });

            modelBuilder.Entity("ERP.Domain.Model.Employee", b =>
                {
                    b.Navigation("CompanyWarehouseStocks");

                    b.Navigation("MaintenanceEmployees");

                    b.Navigation("ProjectEmployees");

                    b.Navigation("ProjectFinancialSnapshots");

                    b.Navigation("ProjectOrderRequests");

                    b.Navigation("ProjectWarehouseStocks");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment", b =>
                {
                    b.Navigation("EquipmentPurchaseItem");

                    b.Navigation("Equipment_Maintenances");

                    b.Navigation("ProjectEquipment");
                });

            modelBuilder.Entity("ERP.Domain.Model.EquipmentPurchase", b =>
                {
                    b.Navigation("EquipmentPurchaseItems");

                    b.Navigation("EquipmentPurchasePayments");
                });

            modelBuilder.Entity("ERP.Domain.Model.Equipment_Maintenance", b =>
                {
                    b.Navigation("MaintenanceEmployees");
                });

            modelBuilder.Entity("ERP.Domain.Model.Material", b =>
                {
                    b.Navigation("CompanyWarehouseStocks");

                    b.Navigation("MaterialPurchaseItem");

                    b.Navigation("OrderMaterials");

                    b.Navigation("PhaseMaterialRequirements");

                    b.Navigation("ProjectWarehouseStocks");

                    b.Navigation("SupplierMaterials");
                });

            modelBuilder.Entity("ERP.Domain.Model.MaterialPurchase", b =>
                {
                    b.Navigation("MaterialPurchaseItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_1_Project_Site_Management.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Domain.Model.Module_2__Procurement_Inventory.ProjectWarehouseStock", b =>
                {
                    b.Navigation("MaterialConsumptions");
                });

            modelBuilder.Entity("ERP.Domain.Model.Phase", b =>
                {
                    b.Navigation("ProjectPhases");
                });

            modelBuilder.Entity("ERP.Domain.Model.Project", b =>
                {
                    b.Navigation("ContractProject")
                        .IsRequired();

                    b.Navigation("FinancialSnapshots");

                    b.Navigation("ProjectEmployees");

                    b.Navigation("ProjectEquipment");

                    b.Navigation("ProjectOrderRequests");

                    b.Navigation("ProjectPhases");

                    b.Navigation("ProjectWarehouses");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectOrderRequest", b =>
                {
                    b.Navigation("OrderMaterials");
                });

            modelBuilder.Entity("ERP.Domain.Model.ProjectWarehouse", b =>
                {
                    b.Navigation("ProjectWarehouseStocks");
                });

            modelBuilder.Entity("ERP.Domain.Model.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERP.Domain.Model.Supplier", b =>
                {
                    b.Navigation("EquipmentPurchases");

                    b.Navigation("Equipments");

                    b.Navigation("MaterialPurchases");

                    b.Navigation("SupplierMaterials");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.Client", b =>
                {
                    b.Navigation("ContractProjects");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ERP.Domain.Model._1_Project_Site_Management.ProjectPhase", b =>
                {
                    b.Navigation("MaterialConsumptions");

                    b.Navigation("ProjectExpenses");

                    b.Navigation("ProjectMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
